### ISSUE TITLE
管理员后台在无权限的情况下依然可以进入

### ISSUE THREAD

**Issue by HeyCrab3** [hitokoto-osc/hitokoto-poll-frontend-refactor#168]
![image](https://github.com/hitokoto-osc/reviewer-frontend/assets/107523807/39095ec0-2367-408b-b9f4-da018c13cd56)
这是为什么呢？好神奇啊

**Comment by greenhat616** [comment]
Closed by https://github.com/hitokoto-osc/reviewer-frontend/commit/ca409824fc503bf5c95ec73c024b9b1f841964e8
